In [1]:
import numpy as np

def diagdom(x):
    x = np.array(x)

    diag = np.diag(np.abs(x))
    offdiag = np.sum(np.abs(x), axis = 1) - diag

    if np.all(diag >offdiag):
        return True
    else:
        return False
    
def GaussSeidel(x, y, tol = 0.01, iter = 15):
    if not diagdom(x):
        print('not diag dom')
        return
    
    x = np.array(x)
    y = np.array(y)

    diag = np.diag(x)
    x = -x

    np.fill_diagonal(x,0)
    old = np.zeros(np.shape(x[0]))

    for i in range(iter):
        new = np.array(old)

        for idx, row in enumerate(x):
            new[idx] = ((y[idx] + np.dot(row, new))/diag[idx])

        print(f'{i} iteration')
        print(new)

        dx = np.sqrt(np.dot(new - old, new - old))

        if(dx < tol):
            print('converged')
            return
        
        old = new
    print('not converged lol')
    return

In [2]:
xs = [[6, 3, 2],
     [2, 7, 3],
     [7, 5, 15]]

ys = [8, 5, 10]

GaussSeidel(xs, ys)

0 iteration
[ 1.33333333  0.33333333 -0.06666667]
1 iteration
[ 1.18888889  0.4031746  -0.02253968]
2 iteration
[1.13925926 0.39844293 0.00219803]
3 iteration
[1.13337919 0.38952107 0.00791602]
4 iteration
[1.13593412 0.38634053 0.0077839 ]
converged
